# Generated by Django 5.2.5 on 2025-11-04 16:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('type', models.CharField(choices=[('CC', 'Conta Corrente'), ('DN', 'Dinheiro'), ('CT', 'Cartão Crédito'), ('IN', 'Investimentos')], default='CC', max_length=2, verbose_name='Tipo')),
                ('logo', models.ImageField(default='sem_imagem.png', upload_to='images/', verbose_name='Logotipo')),
                ('opening_balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Saldo Inicial')),
                ('current_balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Saldo Atual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('active', models.BooleanField(default=True, verbose_name='Conta Ativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('essential', models.BooleanField(default=False)),
                ('metod_503020', models.CharField(blank=True, choices=[('50', 'Necessidades'), ('30', 'Desejos'), ('20', 'Poupança / Investimentos')], max_length=10, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=datetime.datetime.now, verbose_name='Data da Transação')),
                ('due_date', models.DateField(default=datetime.datetime.now, verbose_name='Data de Vencimento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago ou Recebido')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
                ('transaction_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('type', models.CharField(choices=[('C', 'Credito'), ('D', 'Debito')], default='D', max_length=1, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('active', models.BooleanField(default=True, verbose_name='Categoria Ativa')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.account', verbose_name='Conta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='finance.category', verbose_name='categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-transaction_date', 'due_date', 'type'],
            },
        ),
    ]
