# Generated by Django 5.2.5 on 2025-11-06 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='essential',
            field=models.BooleanField(default=False, verbose_name='Essencial'),
        ),
        migrations.AlterField(
            model_name='category',
            name='metod_503020',
            field=models.CharField(blank=True, choices=[('50', '50% - Necessidades'), ('30', '30% - Desejos'), ('20', '20% Poupança / Investimentos'), ('00', 'Não se aplica em receitas')], max_length=10, null=True, verbose_name='Método 50/30/20'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.category', verbose_name='Pai'),
        ),
    ]
