# Generated by Django 5.2.5 on 2026-07-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_category_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#3498db', 'Azul'), ('#e74c3c', 'Vermelho'), ('#2ecc71', 'Verde'), ('#f39c12', 'Laranja'), ('#9b59b6', 'Roxo'), ('#1abc9c', 'Turquesa'), ('#e91e63', 'Rosa'), ('#f1c40f', 'Amarelo'), ('#00bcd4', 'Ciano'), ('#3f51b5', 'Índigo')], default='#3498db', max_length=7, verbose_name='Cor'),
        ),
    ]
