# Generated by Django 5.2.5 on 2026-07-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('investimento', 'Investimentos')], max_length=15, verbose_name='Tipo de Categoria'),
        ),
    ]
