# Generated by Django 5.2.5 on 2026-07-01 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_category_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3498db', max_length=7, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='category',
            name='metod_503020',
            field=models.CharField(blank=True, choices=[('50', '50% - Necessidades'), ('30', '30% - Desejos'), ('20', '20% - Poupança / Investimentos'), ('00', 'Não se aplica em receitas')], max_length=10, null=True, verbose_name='Método 50/30/20'),
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Mês')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planejamento',
                'verbose_name_plural': 'Planejamentos',
                'ordering': ['year', 'month', 'category__name'],
                'unique_together': {('user', 'month', 'year', 'category')},
            },
        ),
    ]
