# Generated by Django 5.2.5 on 2026-07-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_category_color_alter_category_metod_503020_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='affects_balance',
            field=models.BooleanField(default=True, help_text='Indica se esta categoria altera o saldo das contas', verbose_name='Altera Saldo'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_demonstrative',
            field=models.BooleanField(default=False, help_text='Indica se esta categoria é um demonstrativo', verbose_name='Demonstrativo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Transação Ativa'),
        ),
    ]
