# Generated by Django 5.2.5 on 2026-07-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_add_affects_balance_and_is_demonstrative_to_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='affects_balance',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_demonstrative',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('investimento', 'Investimentos'), ('transitoria', 'Transitória')], max_length=15, verbose_name='Tipo de Categoria'),
        ),
    ]
