# Generated by Django 5.2.5 on 2026-07-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_transitoria_and_remove_affects_balance_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='current_balance',
        ),
    ]
