# Generated by Django 5.2.5 on 2026-07-24 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_current_balance_from_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_batch', models.DateTimeField(auto_now_add=True, verbose_name='Data da Importação')),
                ('bank_fit_id', models.CharField(max_length=255, verbose_name='ID do Banco')),
                ('transaction_date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('transaction_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('type', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], max_length=1, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('matched', 'Conciliada'), ('ignored', 'Ignorada'), ('imported', 'Importada')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='Conta')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transaction', verbose_name='Transação Conciliada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação Importada',
                'verbose_name_plural': 'Transações Importadas',
                'ordering': ['transaction_date'],
            },
        ),
    ]
