# Generated by Django 5.2.5 on 2026-08-24 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_imported_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data da Transação'),
        ),
    ]
