# Generated by Django 5.2.5 on 2026-08-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_transaction_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='spending_type',
            field=models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável')], default='variavel', max_length=10, verbose_name='Tipo de Gasto'),
        ),
    ]
