# Generated by Django 5.2.5 on 2026-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_category_spending_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='include_in_emergency_reserve',
            field=models.BooleanField(default=False, verbose_name='Considerar na reserva de emergência'),
        ),
        migrations.AddField(
            model_name='account',
            name='include_in_liquidity',
            field=models.BooleanField(default=False, verbose_name='Considerar na liquidez disponível'),
        ),
    ]
