# Generated by Django 5.2.5 on 2026-08-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_data_mark_default_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installment_group',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Grupo de Parcelas'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nº da Parcela'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_installments',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total de Parcelas'),
        ),
    ]
