# Generated by Django 4.2 on 2024-07-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["create_at", "title"],
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
            },
        ),
    ]
