# Generated by Django 4.2 on 2024-10-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_rename_create_at_subject_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="ativo",
            new_name="active",
        ),
    ]
