# Generated by Django 4.2 on 2024-10-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_rename_ativo_subject_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="course",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
