# Generated by Django 4.2 on 2025-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_note_options_rename_create_at_note_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
        migrations.AddField(
            model_name="note",
            name="order",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
